### ISSUE TITLE
Does not pick up SNS queues defined with display name in YML

### ISSUE THREAD

**Issue by darbio** [mj1618/serverless-offline-sns#10]
As per the [docs](https://serverless.com/framework/docs/providers/aws/events/sns/#sns) SNS queues can be defined inline, causing the SNS queues to be created if they do not already exist.

These aren't picked up by the project and no subscriptions are set up.

Does not work:
```
  wp-shared-email:
    handler: functions/workers/shared/email/handler.index
    events:
      - sns:
          topicName: ${self:custom.sns-topic-shared-email}
          displayName: SNS topic for sending email
```

Causes error:

```
Serverless: INFO[serverless-offline-sns]: unsupported config: [object Object]
```

Works:
```
  wp-event-sink:
    handler: functions/workers/shared/event-sink/handler.index
    events:
      - sns: ${self:custom.sns-topic-website-submit-survey}
```
