### ISSUE TITLE
Documentation for connection to AWS

### ISSUE THREAD

**Issue by kevinlu1211** [mj1618/serverless-offline-sns#101]
After reading through the source code I was able to get an SNS hosted in AWS to trigger my local function as the documentation wasn't very clear

Here is the configuration I used:
```
serverless-offline-sns:
    sns-endpoint: sns.${self:provider.region}.amazonaws.com
    sns-subscribe-endpoint: <ngrok_url>
    remotePort: 80
    localPort: <ngrok_port>
    accountId: ${self:provider.accountId}
```

Example usage:

1. Use ngrok: `ngrok http 4002`

2. Setup config like so:
```
serverless-offline-sns:
    sns-endpoint: sns.${self:provider.region}.amazonaws.com
    sns-subscribe-endpoint: xxxxxxxx.ngrok.io
    remotePort: 80
    localPort: 4002
    accountId: ${self:provider.accountId}
```

Happy to make the PR
