### ISSUE TITLE
SNS filterPolicy not working

### ISSUE THREAD

**Issue by drieshooghe** [mj1618/serverless-offline-sns#103]
When I use a lambda function to push a message (with an attribute) to an SNS topic and have two other lambda's listening to those topics based on attribute filtering, the first lambda in the configuration always gets triggered.

The logs however indicate that the filterPolicy get loaded and the attributes end up in the consumed message.

One of the subscribing lambda's:
```yml
name: subscriberA
handler: src/subscriberA.handler
memorySize: 256
timeout: 10
events:
  - sns:
      arn:
        Fn::Join:
          - ":"
          - - "arn:aws:sns"
            - Ref: "AWS::Region"
            - Ref: "AWS::AccountId"
            - "EventTopic"
      topicName: EventTopic
      filterPolicy:
        name:
          - "a"
```
