### ISSUE TITLE
Create topics defined in Resources section of serverless.yml

### ISSUE THREAD

**Issue by blair55** [mj1618/serverless-offline-sns#107]
I notice that the plugin will automatically create topics for function handlers with an `sns` trigger.

Is there a way to have the plugin automatically create topics defined under the `Resources` section of my serverless file?

```
resources:
  Resources:

    MyTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: my-topic
```

I'm thinking this would be similar to the `migrate` property of the `serverless-dynamodb-local` plugin which instructs the plugin to create tables defined by the resources section.

[https://github.com/99xt/serverless-dynamodb-local#migrations-sls-dynamodb-migrate](https://github.com/99xt/serverless-dynamodb-local#migrations-sls-dynamodb-migrate)
