### ISSUE TITLE
lambda is not triggered for sns topic

### ISSUE THREAD

**Issue by nelsongallardo** [mj1618/serverless-offline-sns#113]
I'm using python, and I have the latest version of `serverless-offline-sns` that supports python, and I have the following yml

```
service: slackbot

plugins:
 - serverless-python-requirements
 - serverless-offline-sns
 - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7

custom:
  serverless-offline-sns:
    port: 4002 # a free port for the sns server to run on
    debug: true

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
  pong:
    handler: handler.pong
    events:
        - sns: topic
```

`Ping` function works correctly, I can see it pushes the event to the local SNS from the logs. But then nothing happens, and the `pong` function never gets triggered.

**Comment by LordAndreasOtten** [comment]
ive the same issue with my nodejs app sadly

**Comment by LordAndreasOtten** [comment]
Although i got it to work by pushing to my localstack env instead of sns from sns-offline

**Comment by apoffa** [comment]
Same issue. The lambda gets subscribed, the event is correctly fired and no errors are shown. I've also tried with a different end-point but the listener lambda isn't called. It works perfectly when deployed.

**Comment by jeffster23** [comment]
I was able to get this working with latest commit of this repo (https://github.com/mj1618/serverless-offline-sns/commit/0e75fe661bbcd522d2b7e168cc2946f2db0aa460).

My serverless.yml is setup much like yours. The order of plugins listed under `custom` has sometimes hard-to-anticipate implications. My plugins are listed as:

```
plugins:
  - serverless-offline
  - serverless-offline-sqs
  - serverless-offline-sqs-dlq
  - serverless-offline-sns
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-s3-local
  - serverless-offline-ssm-parameter-store
  - serverless-plugin-resource-tagging
```

As for the function itself:

```
sendSimulatedEvents:
  name: send-simulated-events-lambda
  handler: handler.simulator
  events:
    - sns:
        topicName: scheduled-events-simulator-topic
        redrivePolicy:
          deadLetterTargetRef: ScheduledEventsReceiverDlqQueueV1
```
