### ISSUE TITLE
Get Function Name return undefined

### ISSUE THREAD

**Issue by flaviofilipe** [mj1618/serverless-offline-sns#139]
https://github.com/mj1618/serverless-offline-sns/blob/5a29200a9861967151a24d81695e96576d2f674d/src/index.ts#L161

**Error message:**
`TypeError: Cannot read property 'runtime' of undefined`

If I create an SNS Subscription, without SQS or SNS function, I can't get the function name.

In CreateHandler I can't get the runtime property:
https://github.com/mj1618/serverless-offline-sns/blob/5a29200a9861967151a24d81695e96576d2f674d/src/index.ts#L378

the _fn_ is undefined.

**My Subscription**
```
mySubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref myTopic
        Endpoint: !GetAtt
          - myConsumer
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'true'
```

**My Topic**
```
    myTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: my-topic
```

**My Queues**
```
    consumerRelease:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: my-queue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt myQueueDlq.Arn
          maxReceiveCount: 3

    myQueueDlq:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: my-queue-dlq
```
