### ISSUE TITLE
Function specific environment variables are not in process.env

### ISSUE THREAD

**Issue by idmontie** [mj1618/serverless-offline-sns#21]
It looks like when a function is being called from SNS, the function specific environment variables for that function are not being added to the `process.env`.

For example, I am running `serverless offline start` with the following `serverless.yml`:

```
functions:
  func1:
    handler: src/func1.handler
    environment:
      VAR_1: "VAR_1"
    events:
      - http: GET /

  func2:
    handler: src/func2.handler
    environment:
      VAR_2: "VAR_2"
    events:
      - sns:
           arn: "XYZ"
```

When `func1` does an `sns.publish` and `func2` is invoked, `func2` will only have `VAR_1` in the `process.env`.

What should happen is that `func2` should have `VAR_2` from its environment settings added to the `process.env`. This seems related to #18.
