### ISSUE TITLE
Can't get it working at all...

### ISSUE THREAD

**Issue by Siyfion** [mj1618/serverless-offline-sns#24]
So I'm using the latest release of the Serverless Framework, with a YAML file that has these key bits:

```yml
custom:
  webpackIncludeModules: true # enable auto including modules
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    dontPrintOutput: false
    port: 4000
  serverless-offline-sns:
    port: 4002
    debug: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sns

functions:
  meanwhileHandler:
    handler: meanwhile.handler
    events:
      - sns:
          topicName: meanwhile_${self:custom.stage}
          displayName: The events triggered from the Meanwhile Creative API
```

Firstly, the ordering of the plugins is deemed *important*, yet the README.md in the library and the example `serverless.yml` have them ordered in two different ways... Which is correct?

Secondly:

* When I call `sls offline` I get the usual `offline` output, but with no SNS-specific logs, making me think that it's not starting up correctly.
* If I call `sls offline-sns start` I can see the SNS topic startup, and receive messages, yet my function doesn't get fired.

**Comment by mj1618** [comment]
Hey thanks for the issue report, I'm trying to reproduce your issue now.

I've updated the readme to make it clear that only the webpack ordering matters.

**Comment by mj1618** [comment]
Hmm sorry but testing on my webpack example works with all latest dependencies - https://github.com/mj1618/serverless-offline-sns-example/compare/webpack-plugin?expand=1

Is there something different in the webpack config that could be causing the issue?
What are the versions of this plugin and your other dependencies?

Unfortunately without being able to reproduce I probably won't be able to help fix the issue.

**Comment by Siyfion** [comment]
@mj1618 Hmm... Okay, here's a slightly more complex version of my YAML file:

```yml
resources:
  Resources:
    DeadLetterQueue:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "Meanwhile Dead Letter Queue"
        TopicName: meanwhile_dlq_${self:custom.stage}

functions:
  stripeHandler:
    handler: stripe.handler
    events:
      - http:
          path: /stripe
          method: post
  meanwhileHandler:
    handler: meanwhile.handler
    onError:
      Ref: DeadLetterQueue
    events:
      - sns:
          topicName: meanwhile_${self:custom.stage}
          displayName: The events triggered from the Meanwhile Creative API
```

Could it be any of the DLQ / Resources stuff causing issues?

package.json versions:
```json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "husky": "^0.15.0-rc.6",
    "jest": "^22.3.0",
    "lint-staged": "^6.1.0",
    "pgtest": "^0.2.2",
    "prettier": "^1.10.2",
    "rewire": "^3.0.2",
    "serverless-offline": "^3.18.0",
    "serverless-webpack": "^4.3.0",
    "snazzy": "^7.0.0",
    "standard": "^10.0.3",
    "webpack": "^3.11.0",
    "webpack-node-externals": "^1.6.0"
  }
```
