### ISSUE TITLE
Not working message filtering 

### ISSUE THREAD

**Issue by tliecau** [mj1618/serverless-offline-sns#41]
Hi!

First off all: Awesome job!

I've encountered an issue:
I'm not sure if this is a bug or this feature is simply not supported but...

I'm using filtering message feature (https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html) and it looks like sns offline triggers all lambdas in the topic. 

I just added to lambda description in serverless.yaml: 
```
Lambda1:
 handler: ...
  events:
   - sns: MyTopic
      filter:
          my_filter_name:
            - myFilterValue

Lambda2
 handler: ...
  events:
   - sns: MyTopic
      filter:
          my_filter_name:
            - myFilterValue2
```
Publishing to sns with parameter my_filter_name=myFilterValue2 triggers both lambdas.
Everything works perfectly on AWS.

Can someone clarify that, please? Is that not supported?
