### ISSUE TITLE
custom port

### ISSUE THREAD

**Issue by eladhaz05** [mj1618/serverless-offline-sns#5]
I want to get the port for the serverless-offline-sns from custom file:
example serverles.yml:
custom:
  globals: ${file(../globals.offline)}
  serverless-offline-sns:
    port: ${self:custom.globals.offline.sns-ports.${self:service}}
    debug: true

I have file globals.offline i nmy project.
When i debug your code i see that the pluging get this :  ${self:custom.globals.offline.sns-ports.${self:service}} as string and not the port from the file.
Is there a way to fix it?

**Comment by mj1618** [comment]
Hey man, yea sure I'll look into it.

**Comment by mj1618** [comment]
Hey @eladhaz05 try version v0.18 and let me know if it fixes your issue.

**Comment by eladhaz05** [comment]
Did you publish this version?

**Comment by mj1618** [comment]
Hmm yes.. maybe it is taking some time for npm to refresh it. I’ll check later and see what’s going on

**Comment by mj1618** [comment]
Hi @eladhaz05 try 0.20 instead

**Comment by eladhaz05** [comment]
The same issue
I got in line: 235 in index.js file in the plugin:
_this.port = ${self:custom.globals.offline.sns-ports.${self:service}} instead of my port

**Comment by mj1618** [comment]
Yea you're right... ok I've test this in the example app, should be fixed in v0.21

Unfortunately the serverless docs are a bit light on this.

**Comment by mj1618** [comment]
Btw I tested with this in my customer section:

```yaml
custom:
  globals:
    offline:
      sns-ports:
        sns-test:
          1234
  serverless-offline-sns:
    port: ${self:custom.globals.offline.sns-ports.${self:service}}
    debug: true
```
