### ISSUE TITLE
aws-cn region issue in topicArn

### ISSUE THREAD

**Issue by likeconan** [mj1618/serverless-offline-sns#97]
Hi, 

I set topicArn in sns like below

```
events:
    handler: main.events
    events:
      - sns: 
          arn: "arn:aws-cn:sns:${opt:region,'cn-northwest-1'}:111111111111:course-saved"

```

however, the SubscriptionArn is still changed into arn:aws:sns:cn-northwest-1:1111111111:course-saved.

Could you help to resolve that?

Thanks a lot
