### ISSUE TITLE
Filter policy doesn't work

### ISSUE THREAD

**Issue by botond-veress** [mj1618/serverless-offline-sns#98]
Hey guys,

Thank you for working on this great library :) It's amazing.

I've checked the previous issues and it looks like the `filterPolicy` support was added to this plugin however I am unable to get it working. The lambda does not get triggered (locally) if I add the `filterPolicy` attribute. If I remove it, it is getting triggered just fine.

Here is my lambda configuration:
```yaml
  sendNotification:
    handler: src/handler/notification.handler
    events:
      - sns:
          arn: ${self:custom.sns.something.arn}
          filterPolicy:
            type:
              - something.created
```

Here is my publish method:
```typescript
    this.sns
      .publish({
        TopicArn: this.arn,
        Message: JSON.stringify({ default: JSON.stringify({ id: 1, type: 'something.created' }) }),
        MessageStructure: 'json'
      })
      .promise()
```

What I am doing wrong? Do you have any suggestions?
Thank you!
